name: Build Whisper WASM

on: [push, workflow_dispatch]

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout whisper.cpp
        uses: actions/checkout@v2

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Download base.en model
        run: |
          mkdir -p models
          wget -O models/ggml-base.en.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin

      - name: Build WASM
        run: |
          make whisper.wasm

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: whisper-wasm
          path: examples/whisper.wasm/
