name: Build Whisper WASM

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
        shell: bash

      - name: Source Emscripten environment
        run: source emsdk/emsdk_env.sh
        shell: bash

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential wget

      - name: Download Whisper model (base.en)
        run: |
          mkdir -p models
          wget -O models/ggml-base.en.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin

      - name: Build WASM (inside examples/whisper.wasm)
        working-directory: examples/whisper.wasm
        run: |
          cmake .
          make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: whisper-wasm
          path: |
            examples/whisper.wasm/whisper.wasm
            examples/whisper.wasm/whisper.js
            ../../models/ggml-base.en.bin
