name: Build Whisper WASM

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install emsdk
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "EMSDK=$PWD/emsdk" >> $GITHUB_ENV
          echo "source $PWD/emsdk/emsdk_env.sh" >> $GITHUB_ENV

      - name: Set up emsdk environment
        run: |
          source emsdk/emsdk_env.sh
          echo "$EMSDK/upstream/emscripten" >> $GITHUB_PATH

      - name: Download whisper model
        run: |
          cd models
          ./download-ggml-model.sh base.en

      - name: Build WASM in examples/whisper.wasm
        working-directory: examples/whisper.wasm
        run: |
          source ../../emsdk/emsdk_env.sh
          cmake .
          make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: whisper-wasm
          path: |
            examples/whisper.wasm/whisper.wasm
            examples/whisper.wasm/whisper.js
            models/ggml-base.en.bin
