name: Build Whisper WASM

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          echo "EMSDK_PATH=$(pwd)" >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential wget

      - name: Download Whisper model
        run: |
          mkdir -p models
          wget -O models/ggml-base.en.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin

      - name: Build Whisper WASM
        working-directory: examples/whisper.wasm
        run: |
          source $EMSDK_PATH/emsdk_env.sh
          emcmake cmake .
          make VERBOSE=1
        shell: bash

      - name: Upload WASM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: whisper-wasm
          path: |
            examples/whisper.wasm/build/whisper.wasm/index.html
            examples/whisper.wasm/build/whisper.wasm/helpers.js
            examples/whisper.wasm/build/bin/libmain.*
            models/ggml-base.en.bin
