name: Build Whisper WASM

on: [push, workflow_dispatch]

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: latest

      - name: Build WASM
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
          make -C examples/whisper.wasm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: whisper-wasm
          path: examples/whisper.wasm/
